name: my_site
description: "A new Flutter project."


publish_to: 'website'













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/pic.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"


  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  assets:
    - assets/

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
